删除无用的头文件，并添加stdint头文件以防止红线警告
wuhanstudio/vt100 pull request #6
Opened 2020-11-29 16:04 UTC by mysterywolf

2020-11-29 21:11 UTC, wuhanstudio requested changes

2020-11-29 21:11 UTC, wuhanstudio commented on src/vt100.h
> +#include <stdint.h>
这里 vt100.c 里面包含了，那可以删掉 vt100.c 里面的 stdint.h

2020-11-29 21:11 UTC, wuhanstudio commented on examples/vt_monitor.c
> -#include <rtdevice.h>
这里 rtdevice.h 确实是多余的，可以删掉，而 rtthread.h 在 rthw.h 里已经包含了。

但是 rtthread.h 还是希望保留，因为包含 rtthread.h 可以直接表明这是 RT-Thread 的例程，而且对编译没有影响。

2020-11-30 05:15 UTC, mysterywolf commented
改好了

2020-11-30 16:55 UTC, wuhanstudio approved these changes

2020-11-30 16:56 UTC, merged