增加vt_clearall vt_clear_scrollback函数 修改数据类型 增加枚举类型
wuhanstudio/vt100 pull request #7
Opened 2020-12-13 10:39 UTC by mysterywolf

2020-12-14 10:24 UTC, wuhanstudio requested changes

2020-12-14 10:24 UTC, wuhanstudio commented on src/vt100.h
确实用 enum 会更加合理，感谢

2020-12-14 10:24 UTC, wuhanstudio commented on src/vt100.h
> -#endif // __VT100_H__
新的 ISO C90 会对 // 注释 直接报错，没注意我还是用的 // 多谢提醒

2020-12-14 10:24 UTC, wuhanstudio commented on src/vt100.c
> + * @param  color off    non-display background (values are available from 40 to 47)
这样表述可能更加简洁：
(ranging from 40 to 47)

2020-12-14 10:24 UTC, wuhanstudio commented on src/vt100.c
> + * @param col destination column number, started from 0
starting from 0

2020-12-14 10:24 UTC, wuhanstudio commented on src/vt100.c
> +
我之后在板子上试试，突然意识到用了 enum 之后，虽然可以正常编译，但有些例程写法可能要改改。

2020-12-14 11:06 UTC, mysterywolf commented on src/vt100.c
> + * @param  color off    non-display background (values are available from 40 to 47)
我直接删掉了，突然发现用了枚举体之后就不需要说明范围了

2020-12-14 11:06 UTC, mysterywolf commented on src/vt100.c
> + * @param col destination column number, started from 0
ok

2020-12-14 11:07 UTC, mysterywolf commented on src/vt100.c
> +
是的，在合并之前需要对当前代码打一个版本

2021-02-10 22:37 UTC, wuhanstudio requested changes

2021-02-10 22:37 UTC, wuhanstudio commented on examples/vt_sl.c
> +MSH_CMD_EXPORT(sl, Steam Locomotive)
这里编译报错，函数名是 vt_sl

2021-02-11 05:02 UTC, mysterywolf commented on examples/vt_sl.c
> +MSH_CMD_EXPORT(sl, Steam Locomotive)
已经修复

2021-02-11 09:01 UTC, merged